### ISSUE TITLE
Test of the circuit breaker fails

### ISSUE THREAD

**Issue by hjoly2003** [spring-guides/gs-cloud-circuit-breaker#2]
Hi, when doing a _mvn clean intall_ under gs-cloud-circuit-breaker-master/complete/reading, the tests fail:

    APPLICATION FAILED TO START

    Description:
    
    Parameter 0 of constructor in hello.BookService required a bean of type 'org.springframework.cloud.client.circuitbreaker.ReactiveCircuitBreakerFactory' that could not be found.
    
    The injection point has the following annotations:
            - @org.springframework.beans.factory.annotation.Autowired(required=true)
    
The problem is with the circuit breaker factory which is absent of the test context.

I must admit that I'm desperately seeking for a working example of an integration test on a reactive circuit breaker.

Thanks in advance

**Comment by ryanjbaxter** [comment]
I am not able to reproduce this, I can build the reading project fine.  You can look to the spring cloud circuitbreaker repo for plenty of examples using circuitbreaker in integration tests
