### ISSUE TITLE
Multiple "Unresolved directive in <stdin>" on spring.io/guides/gs/cloud-circuit-breaker

### ISSUE THREAD

**Issue by kongslund** [spring-guides/gs-cloud-circuit-breaker#5]
On https://spring.io/guides/gs/cloud-circuit-breaker/, I currently see multiple AsciiDoc errors like this screenshot:

<img width="773" alt="Screen Shot 2021-11-20 at 4 42 05 PM" src="https://user-images.githubusercontent.com/1836149/142726688-86066af2-9549-49e5-b22f-cc9c10566c82.png">

**Comment by Buzzardo** [comment]
Fixed in a later commit.
